{% set name = "em-websocket" %}
{% set version = "0.5.2" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 6bae6d8dd9c05c0d1619aef91903c82542de7a15fa92e0110d13a8324eafe1d5

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-eventmachine >=0.12.9
    - rb-http_parser.rb >=0.6.0,<0.7

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: EventMachine based WebSocket server

  doc_url: http://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/igrigorik/{{ name }}

extra:
  recipe-maintainers:
    - sodre
