travis:
  secure:
    BINSTAR_TOKEN: jWiY581i4kpzicPizSz5pz4/lB5ff7B5c2CDubGfUowqs3f9awm48YCkPqkoQy1s1fd80djXcEFXM38n7bkXUv1HYhzK05pmE+3qFbtU2I3zPZ6gfTcfQ70L1EhC0GKJqfrEkEtEGRj4aiTSqrZuR4jxAMvfTxTZp1NUDDL8HKG2hhSSlQGctzNTZWOZhRWagV8Zb2gWeDAcWIJuXnrPkFHsd7aiJHcfGQrV3V1NJXbJsqu43SF3pi/mDphuiEg9/EHr4MH/C/UNb7NPT33zrIU1tiYhUzcMxvrOoT+s2yE3GO+x8vLA1azgONhwvuLhGKESbqxkv5az9Fhcmocjs1uEIiNRNjJVk6sdORW/HV4MZJ4f+xhY5zhBIA+C1T8p2F9ykPMSk2y0VHup8f8ksbMWiC/Rsr5eKiZ/S2e5YmfU4wspFJsgUSeOfgkmcQliok/aKVPSdpi74n7bZ/vOg8uOWvF6+oRJGdCnDVamf+IpVNO8I8FUeCWmXEyiuve8fVNlZUHP56r08558DKkXKFXP4JBoextIZJwE+FN2vT3me073N511hZQ45dpI9jYX6DaMdKYTTy80+ZfdjA6WVLSvsp6ClZRDl9HLF7RQbWqijdN2blSnnQ3gX/D/moHx1NiAwr+lS/Q/H9WQr7Y+oja9LYGsgICI5Xsm3mwsbG0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
